nmea.log:
  parameters: []
  counter:
    fix: 120
  topics:
    fix:
      latitude:
        max: 48.7734
        min: 48.7733
trimble.log:
  parameters:
    - use_trimble_messages:=True
  counter:
    fix: 120
    trimble_moving_base: 120
  topics:
    fix:
      latitude:
        max: 48.7734
        min: 48.7733
    trimble_moving_base:
      yaw:
        min: 1.2
        max: 1.3
ublox.log:
  parameters:
    - use_ublox_messages:=True
  counter:
    fix: 120
    ublox_relpos: 120
  topics:
    fix:
      latitude:
        max: 48.7734
        min: 48.7733
    ublox_relpos:
      carr_soln:
        val: 2
